service: awslamdagituhub
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'